script: bundle exec rake build
rvm:
- ruby-2.3.7
- ruby-2.4.4
- ruby-2.5.1
- ruby-head
- jruby-head
deploy:
- provider: rubygems
  gemspec: rspec-http_helpers.gemspec
  skip_cleanup: true
  api_key:
    secure: "lvhxpMV52U1d9ygkoSX3Y9RYWlDVuZvbFikDgyIDlVz0v34kmqRllynA38xUEaJfNp+M43tYehJfqn492oh2tT7Sxhlt3RQX/H/nVyc8W/K20mDMJcvNe//o9Wj4u3xfZ8dovc1/URhM9EzrBHSq85rZrNxOb2H7xkUMF/FsUbPnaX1+/vTp2ohDncZyGv9y1/znsy9Fdmp+/cObM9nBI5OIjf7/vXpWAWFwBTdX3XzS9C30V/1VYMNEhLzVAT+FoEsOucchUdL/6K0tLCs6O+pEpOljuneAj4WEe9Mghp43VOcX6/XgZ9EvxvnHKTveCF3e9bMyIozusPyKk7cHRAHLgVN6asHglc1N/8aBHolX8VJW4yC6QFgC1FZWhCfi8JUzSsnXxRImrhh3IBG6YX71sU60O9X/WnwABnHjJUS5MFJF3UrzcqtqLUJMvjX5OiIQWfJEBtVAMSvPpc7qo8FmsF7EnHrVciToEc4KMKQLgVgooQk+dlWT+dOWG4pMwZFum/XvDa084FTKRrp93igsG+IjjttseY+8wXthPAvh9BwZprS60rDEjBdDCVUiwsoA7v7Kpqb3GFYPZZWn8KBIt+THvJ1ke7euGb3FP4u7H9yEqeSfJf9iPWnpnizhAzEsCVUdK4tdCUYBC10pFwaub5cjAZkW0l6SJjFpq84="
  on:
    ruby: ruby-2.5.1
    branch: master
    tags: true
- provider: releases
  skip_cleanup: true
  fileglob: true
  file:
  - docs.tgz
  - rspec-http_helpers-*.gem
  api_key:
    secure: "a7XaG7Q6HERqsPTw/UBeGz0Ar0j7fRELbsYdhNlilGx3/T5+9i/rqOkXB23LXti1zqLiWkDlmUANKGbTMMngTt0lwjcuNHckD3fX6N6VbsVyW5hKQFUPrrq4spVF9yemdtRV9DOe40Fs9RyHV4BASlBnLEOH9dVHS2W3BLGrcxLX811k9ruV8wOSdjM0Ei8+c1XX4V9mULaqk9U3wLxlyK/lLuMxFaM/4J7i+hpi/cAKGZai5+6U7UgjISHfECJr41+Tf1OrrUCey3FrELcVUUq8FBDUGJ3vo727LOyBlTLzoNAihkBHvUsqmUPL3ntl5DacKjCro4PIeM3wnEdVXCTX6QzKbGFfjlMs2d4BLRpuxz75gOa9nr54fGD5mXkVR7Y24eaioLwgG+YJNeziPMfIthnzYjrFswas+b43PobM6lTEpnNlBg8EdDqh00GICj+OLfeBP3mdBeqCZXZTl3+Bh15erSvfiRiK10rDMrDfy3yZYLFnftCjMJHOn4T77NTnDXxebO//tobYJsL7wkDdnJR5UDmmT+NJmqPj9GLu54ic/idG0y3i48LpGnyw7Mwl+9ia+HAyo9eg+HYHoiVQ4hJ5VA4u/cHT3XL0NhI0vChPlWaVbiFPb7qUVR5eIHhy2LxAes0MywuMJLMyxaprRd38RdJ3wXfdpKCJdOg="
  on:
    ruby: ruby-2.5.1
    repo: theincognitocoder/rspec-http_helpers
    branch: master
    tags: true
